name: azlogin

on: [workflow_dispatch]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true      
      - run: |
          az webapp list --query "[?state=='Running']"
